L:
  kinematics_solver: iiwa_L_kinematics/IKFastKinematicsPlugin
  kinematics_solver_attempts: 1
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
R:
  kinematics_solver: iiwa_R_kinematics/IKFastKinematicsPlugin
  kinematics_solver_attempts: 1
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
